# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behaivior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=100)),
                ('isUsed', models.IntegerField(choices=[(1, 'used'), (0, 'unused')])),
            ],
            options={
                'ordering': ['isUsed', 'expression'],
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=100)),
                ('isUsed', models.IntegerField(choices=[(1, 'used'), (0, 'unused')])),
            ],
            options={
                'ordering': ['isUsed', 'expression'],
            },
        ),
        migrations.CreateModel(
            name='Middle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=100)),
                ('isUsed', models.IntegerField(choices=[(1, 'used'), (0, 'unused')])),
            ],
            options={
                'ordering': ['isUsed', 'expression'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=300)),
                ('isBehavior', models.IntegerField(choices=[(1, 'pos'), (0, 'neg'), (2, 'unk')])),
            ],
            options={
                'ordering': ['isBehavior', 'expression'],
            },
        ),
    ]
