# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMRCT', '0006_auto_20170921_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='regex',
            name='part',
            field=models.CharField(default='dummy', max_length=10),
        ),
    ]
