# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMRCT', '0007_regex_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regex',
            options={'ordering': ['position', 'expression']},
        ),
        migrations.RenameField(
            model_name='regex',
            old_name='part',
            new_name='position',
        ),
    ]
