# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMRCT', '0008_auto_20170921_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regex',
            options={'ordering': ['position_part', 'expression']},
        ),
        migrations.RenameField(
            model_name='regex',
            old_name='position',
            new_name='position_part',
        ),
    ]
