# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMRCT', '0009_auto_20170921_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middle',
            name='isUsed',
            field=models.IntegerField(choices=[(1, 'used'), (0, 'unused'), (2, 'unusable')]),
        ),
    ]
